config/routes.rb
Rails.application.routes.draw do

  get "/films", to: "main#films", as: 'films'
  get "/photos", to: "main#photos", as: 'photos'
  get "/pricing", to: "main#pricing", as: 'pricing'

  get "/show/:id", to: "main#show", as: 'show'

  resources :asks
  resources :photos

  root to: "main#index"

  scope '/admin' do
    resources :articles do
      collection do
        get "/asks", action: "asks"
        get "/answer", action: "new_answer"
        get "/edit_answer", action: "edit_answer"
      end
    end

    get "/", to: "articles#index"
  end

end

app/models/article.rb
class Article < ApplicationRecord

  has_many :photos

  def self.tabs
    [
      ["필름", "films"],
      ["포토", "photos"],
      ["견적", "pricing"]
    ]
  end

  def self.categories
    { 
      "필름": [
        ["카본", "carbon"],
        ["우드", "wood"],
        ["기타", "etc"]
      ],
      "포토": [
        ["국산차", "domestic"],
        ["수입차", "imported"]
      ],
      pricing: [
        ["경차", "compact"],
        ["중형차", "midsize"],
        ["대형차", "fullsize"],
        ["수입차", "imported"]
      ]
    }
  end

  def category_name
    {
      "films": "필름",
      "photos": "포토",
      "pricing": "견적",
      "carbon": "카본",
      "wood": "우드",
      "etc": "기타",
      "domestic": "국산차",
      "imported": "수입차",
      "compact": "경차",
      "midsize": "중형차",
      "fullsize": "대형차"
    }[self.category.to_sym]
  end

  def tab_name
    {
      "films": "필름",
      "photos": "포토",
      "pricing": "견적",
      "carbon": "카본",
      "wood": "우드",
      "etc": "기타",
      "domestic": "국산차",
      "imported": "수입차",
      "compact": "경차",
      "midsize": "중형차",
      "fullsize": "대형차"
    }[self.tab.to_sym]
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  layout 'admin'

  def asks
    @asks = Ask.all.q

    @asks = @asks.x if params[:term] == "wait"
    @asks = @asks.c if params[:term] == "answered"

    @asks = @asks.order("id desc")
  end

  def new_answer
    @question = Ask.find(params[:ask_id])
    @ask = Ask.new(question_id: @question.id)
  end

  def edit_answer
    @question = Ask.find(params[:ask_id])
    @ask = Ask.find(params[:answer_id])
  end


  def index
    @articles = Article

    @articles = @articles.where(tab: params[:tab]) if params[:tab].present?
    @articles = @articles.where(category: params[:cate]) if params[:cate].present?

    @articles = @articles.order("id desc")
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to articles_path
    else
      flash[:notice] = @article.errors.values.flatten.to_sentence
      render action: :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    params[:article][:photo_ids] = params[:article][:photo_ids].split(",")
    @article = Article.find(params[:id])

    if @article.update_attributes(article_params)
      redirect_to articles_path
    else
      flash[:notice] = @article.errors.values.flatten.to_sentence
      render action: :new
    end
  end

  private
    def article_params
      params.require(:article).permit!
    end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<li id="<%= dom_id(article) %>" class="article">

  <%= link_to edit_article_path(article) do %>
  <div class="thumb">
    <% article.photos.each do |p| %>
      <%= image_tag(p.url(:thumb)) %>
    <% end %>
  </div>

  <div class="detail">
    <div class="info"><%= article.tab_name %> <%= article.category_name %></div>
    <h4><%= article.title %></h4>

    <div class="content"><%= article.content %></div>
    <% if article.price.present? %>
      <div class="price">가격: <%= article.price%> <%= "<del>#{article.normal_price}</del>" if article.normal_price.present? %></div>
    <% end %>
  </div>
  <% end %>

</li>

app/views/articles/_ask.html.erb
<li class="ask">
  <div class="content">
    <%= nl2br ask.content %>
  </div>
  <% if ask.answered? %>
    <div class="answer">
      ㄴ <%= nl2br ask.answer.content %>
    </div>
    <div class="action">
      <%= link_to "답변수정", edit_answer_articles_path(ask_id: ask.id, answer_id: ask.answer.id), class: "button" %>
    </div>
  <% else %>
    <div class="action">
      <%= link_to "답변하기", answer_articles_path(ask_id: ask.id), class: "button" %>
    </div>
  <% end %>
</li>

app/views/articles/_form.html.erb
<div class="photo_uploader">
  <%= link_to "#upload_photo", id: "photo_upload_indicator", class: "fn upload_indicator", data: { fn: "do_upload", args: "photo_uploader" } do %>
    <div class="finder"><%= icon("fas", "search") %> <span>사진 등록</span></div>
    <div class="progress"><%= icon("fas", "cog") %></div>
  <% end %>

  <%= form_for Photo.new, :html => { :class => "invisible" } do |f| %>
    <input id="photo_uploader" type="file" name="files[]" multiple>
  <% end %>
</div>

<ul id="uploaded_photos">
  <% if @article.photos.present? %>
    <%= render @article.photos %>
  <% end %>
</ul>

<%= form_for @article do |f| %>
  <div class="field">
    <%= f.text_field :photo_ids %>
  </div>

  <div class="field">
    <%= f.select :tab, options_for_select(Article.tabs, @article.tab), {}, class: "select" %>
  </div>

  <div class="field">
    <%= f.select :category, grouped_options_for_select(Article.categories, @article.category), {}, class: "select" %>
  </div>

  <div class="field">
    <%= f.text_field :title, class: "text", autocomplete: "off", placeholder: "제목" %>
  </div>

  <div class="field">
    <%= f.text_field :normal_price, class: "text", autocomplete: "off", placeholder: "정상가격" %>
  </div>

  <div class="field">
    <%= f.text_field :price, class: "text", autocomplete: "off", placeholder: "할인가격" %>
  </div>

  <div class="field">
    <%= f.text_area :content, class: "text smartfocus", placeholder: "내용", autocomplete: "off", rows: 3 %>
  </div>

  <div class="actions">
    <%= button_tag class: 'submit' do %>
      <%= icon("fas", "check") %> <%= @article.new_record? ? "등록" : "수정" %>
    <% end %>
  </div>

<% end %>

<script>
  initFns();
  $('#photo_uploader').fileupload({
    url: '/photos',
    dataType: 'json',
    paramName: 'photo[attachment][]',
    sequentialUploads: false,
    add: function(e, data) {
      if (/\.(pn|jpe?)?g(if|$)/i.test(data.files[0].name)) {
        data.submit();
      } else {
        alert('png, jpg, gif 만 가능합니다');
      }
    },
    start: function() {
      $('#photo_upload_indicator').addClass("active");
    },
    progressall: function(e, data) {
      var progress = parseInt(data.loaded / data.total * 100, 10);
      var progress_min = $('#photo_upload_indicator .progress').width() / $('#photo_upload_indicator').width() * 100;
      if (progress > progress_min) {
        $('#photo_upload_indicator .progress').css('width', progress + '%');
      }
    },
    done: function(e, data) {
      var images = [];

      $.each(data.result.files, function(index, file) {
        $("ul#uploaded_photos").append(file.html);
        putCSV("article_photo_ids", file.photo_id);
      });

    },
    stop: function(e, data) {
      $('#photo_upload_indicator .progress').css('width', '100%');
      setTimeout(function(){
        $('#photo_upload_indicator').removeClass("active", function() {
          $(this).find('.progress').css('width', '0%');
        });
      }, 500);
    }
  }).prop('disabled', !$.support.fileInput).parent().addClass($.support.fileInput ? undefined : 'disabled');
</script>

app/views/articles/asks.html.erb
<div id="asks" class="nav">
  <%= link_to "전체", asks_articles_path, class: path_match?(term: nil)  %><!--
  --><%= link_to "미답변", add_query(term: "wait"), class: path_match?(term: "wait") %><!--
  --><%= link_to "답변", add_query(term: "answered"), class: path_match?(term: "answered") %>
</div>

<ul class="asks">
  <%= render partial: 'articles/ask', collection: @asks %>
</ul>

app/views/articles/edit.html.erb
<%= render 'form' %>

app/views/articles/edit_answer.html.erb
<ul class="asks">
  <li class="ask nb">
    <div class="content">
      <%= @question.content %>
    </div>
  </li>
</ul>

<div class="ask">
  <%= form_for @ask do |f| %>
    <%= f.hidden_field :question_id %>
    <%= f.hidden_field :answered %>

    <div class="field">
      <%= f.text_area :content, class: "text smartfocus", placeholder: "답변을 여기에 입력해주세요.", autocomplete: "off", rows: 5 %>
    </div>

    <div class="actions">
      <%= button_tag class: 'submit' do %>
        <%= icon("fas", "check") %> <%= @ask.new_record? ? "답변등록" : "답변등록" %>
      <% end %>
    </div>

  <% end %>
</div>

app/views/articles/index.html.erb
<div id="tabs" class="nav">
  <%= link_to "전체", articles_path, class: path_match?(tab: nil) %><!--
  --><%= link_to "필름", add_query(tab: "films", cate: nil), class: path_match?(tab: "films") %><!--
  --><%= link_to "포토", add_query(tab: "photos", cate: nil), class: path_match?(tab: "photos") %><!--
  --><%= link_to "견적", add_query(tab: "pricing", cate: nil), class: path_match?(tab: "pricing") %>
</div>

<% if params[:tab].present? && params[:tab] == "films" %>
<div id="films" class="nav categories">
  <%= link_to "카본", add_query(cate: "carbon"), class: path_match?(cate: "carbon") %><!--
  --><%= link_to "우드", add_query(cate: "wood"), class: path_match?(cate: "wood") %><!--
  --><%= link_to "기타", add_query(cate: "etc"), class: path_match?(cate: "etc") %>
</div>
<% end %>

<% if params[:tab].present? && params[:tab] == "photos" %>
<div id="photos" class="nav categories">
  <%= link_to "국산차", add_query(cate: "domestic"), class: path_match?(cate: "domestic") %><!--
  --><%= link_to "외제차", add_query(cate: "imported"), class: path_match?(cate: "imported") %>
</div>
<% end %>

<% if params[:tab].present? && params[:tab] == "pricing" %>
<div id="pricing" class="nav categories">
  <%= link_to "경차", add_query(cate: "compact"), class: path_match?(cate: "compact") %><!--
  --><%= link_to "중형차", add_query(cate: "midsize"), class: path_match?(cate: "midsize") %><!--
  --><%= link_to "대형차", add_query(cate: "fullsize"), class: path_match?(cate: "fullsize") %><!--
  --><%= link_to "외제차", add_query(cate: "imported"), class: path_match?(cate: "imported") %>
</div>
<% end %>

<div id="action-button">
  <%= link_to "콘텐츠등록", new_article_path, class: "button" %>
</div>

<ul class="articles">
  <%= render @articles %>
</ul>

app/views/articles/main.html.erb
articles main

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/new_answer.html.erb
<ul class="asks">
  <li class="ask nb">
    <div class="content">
      <%= @question.content %>
    </div>
  </li>
</ul>

<div class="ask">
  <%= form_for @ask do |f| %>
    <%= f.hidden_field :question_id %>
    <%= f.hidden_field :answered %>

    <div class="field">
      <%= f.text_area :content, class: "text smartfocus", placeholder: "답변을 여기에 입력해주세요.", autocomplete: "off", rows: 5 %>
    </div>

    <div class="actions">
      <%= button_tag class: 'submit' do %>
        <%= icon("fas", "check") %> <%= @ask.new_record? ? "답변등록" : "답변등록" %>
      <% end %>
    </div>

  <% end %>
</div>