config/routes.rb
Rails.application.routes.draw do

  get "/films", to: "main#films", as: 'films'
  get "/photos", to: "main#photos", as: 'photos'
  get "/pricing", to: "main#pricing", as: 'pricing'

  get "/show/:id", to: "main#show", as: 'show'

  resources :asks
  resources :photos

  root to: "main#index"

  scope '/admin' do
    resources :articles do
      collection do
        get "/asks", action: "asks"
        get "/answer", action: "new_answer"
        get "/edit_answer", action: "edit_answer"
      end
    end

    get "/", to: "articles#index"
  end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crazyfactory</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :head %>
    <meta name="viewport" content="user-scalable=yes, width=375" />
  </head>

  <body class="admin">
    <div id="gnb">
      <%= link_to "#{icon('fas', 'skull')}사이트".html_safe, articles_path %><!--
      --><%= link_to "#{icon('fas', 'edit')}콘텐츠".html_safe, articles_path, class: path_match?(controllers: "articles", actions: "index") %><!--
      --><%= link_to "#{icon('fas', 'question')}문의".html_safe, asks_articles_path, class: path_match?(controllers: "articles", actions: "asks") %>
    </div>

    <header>
      <h1><%= link_to "WRV", articles_path %></h1>
    </header>

    <section class="main">
      <%= yield %>
    </section>

    <footer class="main">
      <address>
        <%= link_to SITENAME, root_path %>
      </address>
    </footer>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crazyfactory</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :head %>
    <meta name="viewport" content="user-scalable=yes, width=375" />
  </head>

  <body>
    <div id="gnb">
      <%= link_to "#{icon('fas', 'skull')}소개".html_safe, root_path, class: path_match?(controllers: "main", actions: "index") %><!--
      --><%= link_to "#{icon('fas', 'tape')}필름".html_safe, films_path, class: path_match?(controllers: "main", actions: "films") %><!--
      --><%= link_to "#{icon('fas', 'camera-retro')}포토".html_safe, photos_path, class: path_match?(controllers: "main", actions: "photos") %><!--
      --><%= link_to "#{icon('fas', 'dollar-sign')}견적".html_safe, pricing_path, class: path_match?(controllers: "main", actions: "pricing") %><!--
      --><%= link_to "#{icon('fas', 'question')}문의".html_safe, new_ask_path, class: path_match?(controllers: "asks") %>
    </div>


    <header>
      <h1><%= link_to "크레이지팩토리", root_path %></h1>
    </header>

    <div id="fullcover"></div>
    <section class="main">
      <%= yield %>
    </section>

    <footer class="main">
      <address>
        <%= link_to SITENAME, root_path %>
      </address>
    </footer>
  </body>
</html>